apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kuro-cluster
  region: ap-northeast-1
  version: "1.29"

managedNodeGroups:
  - name: ng-kuro
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub

iam:
  withOIDC: true